[package]
name = "ssssh"
version = "0.1.0"
authors = ["yskszk63 <yskszk63@gamil.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "0.2.0-alpha"
futures-preview = "0.3.0-alpha.18"
bytes = "0.4"
rand = "0.7"
openssl = "0.10"
failure = "0.1"
ring = "0.16"
log = "0.4"
async-trait = "0.1"

[dev-dependencies]
tokio-test = "0.2.0-alpha"
tokio-net = { version="0.2.0-alpha", features=["process"] }
env_logger = "0.6"
bencher = "0.1"

[[bench]]
name = "bench"
harness = false
