name: tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install rust nightly
      run: rustup install nightly

    - name: Install grcov
      run: |
        mkdir $HOME/grcov
        curl -SsL "$GRCOV_URL" | tar -jxf - -C $HOME/grcov
        chmod +x $HOME/grcov/grcov
        echo "::add-path::$HOME/grcov"
      env:
        GRCOV_URL: 'https://github.com/mozilla/grcov/releases/download/v0.5.15/grcov-linux-x86_64.tar.bz2'

    - name: Check format
      run: cargo fmt -- --check

    - name: Run grcov
      run: |
        cargo +nightly build
        cargo +nightly test
        grcov ./target/debug -s . -t lcov --llvm --branch --ignore-not-existing -o lcov.info
      env:
        CARGO_INCREMENTAL: "0"
        RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"

    - uses: codecov/codecov-action@v1
      with:
        file: ./lcov.info
# vim: set sw=2 ts=2 sts=2:
